### ISSUE TITLE
VS code can't connect marketplace

### ISSUE THREAD

**Issue by ssgh98** [microsoft/vsmarketplace#125]
Issue Type: <b>Performance Issue</b>

Vs code can't connecct marketplace, how do I fixed this?

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by isidorn** [comment]
We closed this issue because it is a question about using VS Code rather than an issue or feature request. Please search for help on StackOverflow, where the community has already answered thousands of similar questions. You may find their guide on asking a new question helpful if your question has not already been asked. See also our issue reporting guidelines.

Happy Coding!
