### ISSUE TITLE
Purchasing Licenses fail with error: we are unable to to load the change quantity experience

### ISSUE THREAD

**Issue by ThomasSkyldahl** [microsoft/vsmarketplace#230]
**Describe the bug**
The checkout flow for purchasing licenses is very slow and fails at some point with the following issue: 

`
Sorry, we are unable to load the change quantity experience. Give it few mins and then try again. Error: [{"errorMessage":"An undefined error occurred while attempting to connect to the server. Status code 0: error.","errorMethod":"BuyCustomizationSource.VSSCommerce.getItemPrice","errorType":"SystemError","errorTrace":"{\"stack\":\"TFS.WebApi.Exception: An undefined error occurred while attempting to connect to the server. Status code 0: error.\\n    at g (https://cdn.vsassets.io/bundles/vss-bundle-common-vnIV3f_0Re0f0N_kwWxCAdAhsb8zaiTi8xoAQ8W7HIOE=:820:735)\\n    at https://cdn.vsassets.io/bundles/vss-bundle-common-vnIV3f_0Re0f0N_kwWxCAdAhsb8zaiTi8xoAQ8W7HIOE=:820:3919\\n    at https://cdn.vsassets.io/bundles/vss-bundle-common-vnIV3f_0Re0f0N_kwWxCAdAhsb8zaiTi8xoAQ8W7HIOE=:820:984\\n    at n._func (https://cdn.vsassets.io/bundles/vss-bundle-common-vnIV3f_0Re0f0N_kwWxCAdAhsb8zaiTi8xoAQ8W7HIOE=:818:217)\\n    at n._invoke (https://cdn.vsassets.io/bundles/vss-bundle-common-vnIV3f_0Re0f0N_kwWxCAdAhsb8zaiTi8xoAQ8W7HIOE=:818:5244)\\n    at https://cdn.vsassets.io/bundles/vss-bundle-common-vnIV3f_0Re0f0N_kwWxCAdAhsb8zaiTi8xoAQ8W7HIOE=:818:4045\",\"message\":\"An undefined error occurred while attempting to connect to the server. Status code 0: error.\",\"name\":\"TFS.WebApi.Exception\",\"status\":0,\"jqXHR\":{\"readyState\":0,\"status\":0,\"statusText\":\"error\"}}"}].`

**To Reproduce**
1. From: https://manage.visualstudio.com/Subscribers
2. Click on 'Change quantity'
3.  Change: [USE YOUR-OWN-SUBSCRIPTION-ID] to a valid subscription ID and load the link. wait for the loading to finish: 'https://marketplace.visualstudio.com/acquisition?itemName=ms.vs-professional-monthly&subscriptionId=[USE YOUR-OWN-SUBSCRIPTION-ID]&source=manage&acquisitionOption=2'

**Expected behavior**
I didn't expect a backend error, but a option to change the license quantity and continue the checkout process

**Screenshots**

![checkout_error](https://user-images.githubusercontent.com/1462997/139671824-15bb9ba0-f570-40ea-9d1e-d74366ecfd1c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - Version 95

**Additional context**
Add any other context about the problem 

here.

**Comment by commissionfactorydavid** [comment]
This issue seems to be because of a CORS error. I can see the following error in the browser console (with some GUIDs redacted):

`Access to XMLHttpRequest at 'https://commerceprodwus21.vscommerce.visualstudio.com/_apis/OfferMeter/OfferMeter/ms.vs-professional-monthly?resourceNameResolveMethod=GalleryId&subscriptionId=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&includeMeterPricing=true&offerCode=&tenantId=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&objectId=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX' from origin 'https://marketplace.visualstudio.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

I was able to complete a purchase by temporarily disabling CORS in my browser.

**Comment by djhayman** [comment]
This issue seems to be because of a CORS error. I can see the following error in the browser console (with some GUIDs redacted):

`Access to XMLHttpRequest at 'https://commerceprodwus21.vscommerce.visualstudio.com/_apis/OfferMeter/OfferMeter/ms.vs-professional-monthly?resourceNameResolveMethod=GalleryId&subscriptionId=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&includeMeterPricing=true&offerCode=&tenantId=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&objectId=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX' from origin 'https://marketplace.visualstudio.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

I was able to complete a purchase by temporarily disabling CORS in my browser.

**Comment by SergeyJust** [comment]
Disabling CORS was not resolve this issue. 
I'm try many plugins and options. 
Result on screenshot. 

![Screenshot 2021-12-01_18-07-47-813](https://user-images.githubusercontent.com/47122247/144270181-056ac616-3b75-4e01-9134-c70cb0ba68ee.png)


May be your know other way to change subscription  quantity?

**Comment by knilecrack** [comment]
I have the same issue. It was not the problem to buy it but when I want to cancel it it's a CORS problem ?

**Comment by horealisnic** [comment]
I have the same problem, cannot purchase because of CORS error.

**Comment by NeilMacMullen** [comment]
Same issue here - can't understand why this is not being looked at as a priority :-(

**Comment by knilecrack** [comment]
@NeilMacMullen  @horealisnic  did you guys open a ticket for this maybe ?

**Comment by NeilMacMullen** [comment]
@knilecrack Yes - I've opened a ticket and tweeted Azures support.  Still waiting for a response on the support ticket ...

**Comment by knilecrack** [comment]
@NeilMacMullen Yeah, me too. Let's see what happens :)

**Comment by munishgoyal1** [comment]
This issue is being looked at on priority by the subscriptions commerce team. Expecting to have an update soon.

**Comment by NeilMacMullen** [comment]
Just retried and it is now working for me 👍

**Comment by knilecrack** [comment]
It's working for me as well. Looks like issue has been fixed.

**Comment by rheajain** [comment]
Issue is fixed now.

**Comment by AndAShape** [comment]
Still an issue here... 

> Sorry, we are unable to load the change quantity experience. Give it few mins and then try again. Error: [{"errorMessage":"An undefined error occurred while attempting to connect to the server. Status code 0: error.","errorMethod":"BuyCustomizationSource.VSSCommerce.getItemPrice","errorType":"SystemError","errorTrace":"{\"stack\":\"TFS.WebApi.Exception: An undefined error occurred while attempting to connect to the server. Status code 0: error.\\n    at g (https://cdn.vsassets.io/bundles/vss-bundle-common-vWJDoSfx5H_lfbFAM0gFByXcK8TRJw4P135wLC-Xzy8w=:820:735)\\n    at https://cdn.vsassets.io/bundles/vss-bundle-common-vWJDoSfx5H_lfbFAM0gFByXcK8TRJw4P135wLC-Xzy8w=:820:3919\\n    at https://cdn.vsassets.io/bundles/vss-bundle-common-vWJDoSfx5H_lfbFAM0gFByXcK8TRJw4P135wLC-Xzy8w=:820:984\\n    at n._func (https://cdn.vsassets.io/bundles/vss-bundle-common-vWJDoSfx5H_lfbFAM0gFByXcK8TRJw4P135wLC-Xzy8w=:818:217)\\n    at n._invoke (https://cdn.vsassets.io/bundles/vss-bundle-common-vWJDoSfx5H_lfbFAM0gFByXcK8TRJw4P135wLC-Xzy8w=:818:5287)\\n    at https://cdn.vsassets.io/bundles/vss-bundle-common-vWJDoSfx5H_lfbFAM0gFByXcK8TRJw4P135wLC-Xzy8w=:818:4088\",\"message\":\"An undefined error occurred while attempting to connect to the server. Status code 0: error.\",\"name\":\"TFS.WebApi.Exception\",\"status\":0,\"jqXHR\":{\"readyState\":0,\"status\":0,\"statusText\":\"error\"}}"}].

**Comment by cgremmel** [comment]
Same here!

**Comment by AndAShape** [comment]
It's a CORS error again, according to the console.
