### ISSUE TITLE
Change in user-agent header influences the cdn link

### ISSUE THREAD

**Issue by isidorn** [microsoft/vsmarketplace#267]
VS Code changed the request header to be the following:

```
user-agent:VSCode (Code - Insiders)
x-market-client-id:VSCode 1.63.0-insider
x-market-client-version:1.63.0-insider
```

This change causes the MP to give us a different cdn url:
```
https://ms-dotnettools.gallery.vsassets.io/_apis/public/gallery/publisher/ms-dotnettools/extension/csharp/1.23.17/assetbyname/Microsoft.VisualStudio.Code.Manifest
```

This is one was given before and is the correct one:
```
https://ms-dotnettools.gallerycdn.vsassets.io/extensions/ms-dotnettools/csharp/1.23.17/1638537974862/Microsoft.VisualStudio.Code.Manifest
```

@sandy081 and me have verified that the change that causes the problem is the `user-agent`. The addition of `x-market-client-version` has no effect.

To reproduce you can use this VS Code insiders which reproduces the issue all the time. Just try to install the C# extension.
https://az764295.vo.msecnd.net/insider/d09289a2b6dd0e56b2a264a8e9380685498e10d6/VSCodeSetup-x64-1.63.0-insider.exe

As seen in the C# extension issue https://github.com/OmniSharp/omnisharp-vscode/issues/4922
We will revert our user-agent change until we have found the root cause on the MP side https://github.com/microsoft/vscode/issues/138503

**Comment by SaiKanth007** [comment]
I looked into the issue, it has two parts in it

1. VSCode should always include targetPlatform in the asset request calls, if the asset is being requested for a platform specific version. For example, in the below case where we are requesting manifest file

`https://ms-dotnettools.gallery.vsassets.io/_apis/public/gallery/publisher/ms-dotnettools/extension/csharp/1.23.17/assetbyname/Microsoft.VisualStudio.Code.Manifest?targetPlatform=darwin-x64`

2. There are couple of flows where marketplace checks for VSCode version also in the User-Agent. Since we didn't include the version number in the modified User-Agent, this resulted in the issue. You can modify the user agent similar to x-market-client-id as "VSCode 1.63.0-insider" and it should work fine.

I have tested both the parts and they are working fine. Discussed the first point with @sandy081 as well.

**Comment by isidorn** [comment]
@SaiKanth007 this makes sense, can we just come up with a user agent that will work for MP and for us as well.
How about 
```
agent:VSCode 1.63.0-insider (Code - Insiders)
```

Once we settle on this I am fine with closing this issue if @sandy081 agrees.

**Comment by isidorn** [comment]
@SaiKanth007 confirmed this works. We should just self-host on insiders to make sure that we are not breaking anything.
Thus closing this issue and opening this one on the vscode side https://github.com/microsoft/vscode/issues/138591
