### ISSUE TITLE
Cake build verified but badge does not get rendered

### ISSUE THREAD

**Issue by isidorn** [microsoft/vsmarketplace#268]
cake-build got verified as a publisher but there is not verified badge in the marketplace
When you try to install the extension in VS Code the hover says the author is verified, but there is no badge.

@rheajain can you investigate? I believe the issue is on the MP side.

https://marketplace.visualstudio.com/items?itemName=cake-build.cake-vscode

Issue is found by @gep13

![image](https://user-images.githubusercontent.com/1926584/144994815-76050ecd-f50e-4502-b4d2-3e9189194f07.png)

**Comment by gep13** [comment]
@isidorn thank you for raising this issue, appreciate it!

**Comment by chgill-MSFT** [comment]
I looks like the publisher hasn't completed the verification process - either hasn't been approved yet or hasn't validated the TXT record.

The real bug is that we're showing the "This publisher has verified ownership of <domain>" when they have merely input the domain in the **Verified domain** field without completing the process.

@rheajain can you look into this?

**Comment by gep13** [comment]
>@chgill-MSFT said...
I looks like the publisher hasn't completed the verification process - either hasn't been approved yet or hasn't validated the TXT record.

Just to be clear, I am the publisher 😄

The TXT entries have been created. Is there a way to know if the verification process has been attempted, or if there is something else that needs to be done?

**Comment by chgill-MSFT** [comment]
It's likely that the Marketplace team hasn't gotten to reviewing and approving the verification request yet. We had some delays last week due to a data migration. If you successfully validated the TXT record, there should be a line under the input field that says it's being reviewing by the Marketplace team.

Thank you for your patience! However, the tooltip and badge should come together once the request has been approved 🙂

**Comment by gep13** [comment]
@chgill-MSFT I am seeing this when checking in site:

<img width="518" alt="2021-12-07_19-22-06" src="https://user-images.githubusercontent.com/1271146/145092814-561ad43c-eaa6-4f43-9c15-347e1402fa22.png">

Is this what you expect?

**Comment by chgill-MSFT** [comment]
That's right - the line below the input means it has yet to be reviewed. Currently, no action is needed on your part 🙂

**Comment by rheajain** [comment]
> It's likely that the Marketplace team hasn't gotten to reviewing and approving the verification request yet. We had some delays last week due to a data migration. If you successfully validated the TXT record, there should be a line under the input field that says it's being reviewing by the Marketplace team.
> 
> Thank you for your patience! However, the tooltip and badge should come together once the request has been approved 🙂

Yes, that was exactly the issue. We had not reviewed your request. We have now, so you should see the tick in some time :)
@chgill-MSFT I will register a bug for the tooltip issue.

**Comment by gep13** [comment]
Woot!

I can confirm that this is now working!

<img width="707" alt="2021-12-09_07-25-16" src="https://user-images.githubusercontent.com/1271146/145352364-a807f1a7-099b-4269-8568-397eaa48775b.png">

**Comment by rheajain** [comment]
@isidorn This issue is on VS Code side. Before showing the Tooltip, please make sure that `isVerified` flag is true.

**Comment by isidorn** [comment]
@sandy081 can you check if you are respecting the `isVerified` flag for the tooltip as @rheajain suggests?

**Comment by sandy081** [comment]
Yes, we respect the flag from Marketplace and hence the verification badge is not shown. I think I missed it here, fixed it. Thanks.

**Comment by isidorn** [comment]
Ok, thanks for fixing Sandy.
So it seems like we have tackled all the issues here, thus closing this. Thanks
