### ISSUE TITLE
Verifying ownership of a domain with HTTP 308 Permanent redirect

### ISSUE THREAD

**Issue by sebazai** [microsoft/vsmarketplace#276]
Hello,

we are trying to verify `mooc.fi` domain, but the Domain name field doesn't accept `https://mooc.fi` that redirects with HTTP 308 status code to `https://www.mooc.fi/`, we receive the following error:

![image](https://user-images.githubusercontent.com/39335537/145808826-35d45d37-999a-455d-9632-e14b61744b73.png)

**Comment by rheajain** [comment]
@sebazai As a validation we check that the URL you provide give a 200 OK response to the HEAD request call.
We are currently not accepting any subdomain, including 'www', which is why you will also not be able to add `https://www.mooc.fi/` URL as the domain. We are currently reviewing this validation.
In the meantime to get unblocked, can you configure `https://mooc.fi` to give Http response- 200 for its HEAD call.
