### ISSUE TITLE
Could not create publisher

### ISSUE THREAD

**Issue by taoqf** [microsoft/vsmarketplace#31]
**Describe the bug**
I could not create publisher using <https://marketplace.visualstudio.com/manage/createpublisher> because of our gov is blocking us from google.
**To Reproduce**
2. The page will continue loading until timeout. 
3. When click button `Create`, nothing happened.

**Additional context**
I cannot get access to <https://www.google.com/recaptcha/api.js>, so I would not create publisher now. Is there any other way to create publisher?

**Comment by prashantvc** [comment]
Hey @taoqf 
Thanks for reporting the issue, we looking into this. We will keep you posted as soon as possible

**Comment by 330595524** [comment]
Is there any answer to this question？？？

**Comment by prashantvc** [comment]
I have a temporary workaround for you guys, could you contact me on email prchol@microsoft.com?

**Comment by madhurivadaligithub** [comment]
Hi @taoqf 

Are you still facing the issue while creating publisher?

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.

**Comment by Shichien** [comment]
The problem seems to be related to the CAPTCHA verification grid (the nine-square image puzzle) that appears when creating a new publisher. This verification view sometimes fails to appear in browsers like **Microsoft Edge** and **Google Chrome**.

**Solution**:

The CAPTCHA grid displays correctly in **Mozilla Firefox** and **Safari**. If you are unable to see the verification view, the primary troubleshooting step should be to try creating the publisher using a different browser like Firefox or Safari.
