### ISSUE TITLE
Set CORP header with cross-origin value

### ISSUE THREAD

**Issue by isidorn** [microsoft/vsmarketplace#476]
VS Code is becoming cross origin isolated and that resources that we load, such as icons etc, need to signal “ok for being embedded”.
Context https://github.com/microsoft/vscode/issues/158792#issuecomment-1222690949
Reference https://developer.mozilla.org/en-US/docs/Web/HTTP/Cross-Origin_Resource_Policy_(CORP)

So we need the Marketplace to set to set the following header in the response for resources:
`Cross-Origin-Resource-Policy: cross-origin`

Explainer https://web.dev/why-coop-coep/#corp

fyi @SaiKanth007 @jrieken

**Comment by isidorn** [comment]
@SaiKanth007 just informed me he is out until Monday. So I would only expect a response then.

**Comment by anupkmr03** [comment]
Planning to pick this in next milestone. I will keep updating on progress.

**Comment by JatinSanghvi** [comment]
Hi @prashantvc, the fix was committed last week, and will be part of next release.

**Comment by isidorn** [comment]
Awesome. Then let's go ahead and close this issue as completed. Thank you very much 👏

**Comment by JatinSanghvi** [comment]
The fix is deployed. I found that the responses from CDN hosts still does not have the CORP headers set. Seeing failed response, VS Code then tries to query the non-CDN fallback URL which succeeds as it has the CORP headers set now.

Overall, this retrying part stays invisible to the user unless they check the Developer Tools. But this is a problem, as it leads to unnecessary requests to CDN endpoints, increase is time to load extension pages, as the requests need to directly hit the Marketplace service and increase in number of requests on the Marketplace service.

@SaiKanth007, we had some discussion over this in the past. Do you know if we can force update the CDN responses to match them with the original responses?

**Comment by SaiKanth007** [comment]
The assets are by default cached for 1 year in our CDN. I think the asset you might be looking might be an older one and got cached already. Can you try checking for a new asset that got uploaded after your fix?

Once we verify this, we can purge the assets in the CDN. Last time we did a complete purge of our CDN and it didn't take much time to reach the same state as before purging.

**Comment by JatinSanghvi** [comment]
It turns out that this will require adding a CDN configuration to add the CORP header. That should make the browser accept the CDN responses and stop hitting the Gallery service. I will be working on this change.

**Comment by JatinSanghvi** [comment]
The CDN policy is updated for PROD. There's a problem updating CDN policy for PPE for which I will be following up with Verizon support team. Also, China CDN needs to be updated accordingly. The icon file requests to `gallerycdn.vsassets.io` are are working fine now. No requests are being retried on the Gallery service.

![image](https://user-images.githubusercontent.com/20547963/216310760-5b4de96c-d295-46d4-8ab4-8b8d7f060839.png)

Please note that we have added the policy to return CORP headers for icon files only, since that is the only file that seems to be having issues. Please let us know if the filter for including CORP headers needs ever to be relaxed in future.

**Comment by JatinSanghvi** [comment]
Update: All CDNs are updated now. We do not have any pending work connected with this issue.
