### ISSUE TITLE
Transfer Extension to new Publisher

### ISSUE THREAD

**Issue by ybadragon** [microsoft/vsmarketplace#478]
Hello,

My company recently switched AAD instances for ADO and were told our marketplace publisher would follow through with the migration, this did not happen. I've recently learned it is not possible to transfer the entire publisher, however according to [Issue 440](https://github.com/microsoft/vsmarketplace/issues/440) it looks to be possible to transfer our extensions over to a new publisher. Can anyone help me with this process?

**Comment by madhurivadaligithub** [comment]
Hi @ybadragon Thanks for reaching VS Marketplace Support Team.
 If your extensions are VS code , 
 Usually, we do not allow transfer of VSCode extensions since it has following consequences:
->Users will not be able to install the older versions of your extensions that got published before the extension transfer from the VSCode.
I->f this extension is used as a dependency in other extensions by using publisherName.ExtensionName, that would not work.
->You need to update all references to this extension with the new publisherName.
Please confirm if you are okay with the above consequences, then we can go ahead with the transfer extension request.

Or if its ADO extensions, we cannot transfer the extensions between owners by design. 

Please check and confirm on this query?

**Comment by ybadragon** [comment]
Thank you for getting back to me, we were looking to transfer the ADO extension to a new publisher. Can you help me understand the reasoning behind why it's supported for VSCode extensions but not for ADO extensions? To developers everything is just going to the marketplace publisher so thats unexpected to me to be supported by 1 and not the other.

**Comment by madhurivadaligithub** [comment]
@ybadragon We understood but this is design limitation for ADO.

**Comment by madhurivadaligithub** [comment]
@ybadragon Feel free to create a new ticket if you have any other issues.
