### ISSUE TITLE
Support relative path videos on extension pages 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vsmarketplace#494]
## Feature request

Rendered extension readme pages should support videos that use relative paths. We already supported this for images.

[This test extension](https://marketplace.visualstudio.com/items?itemName=bierner.test-test) demonstrates the issue. The markdown in the readme is:

```md
Local video:

<video src="test.mp4"></video>

Local Image: 

<img src="cat.gif">

Remote video:

<video src="https://github.com/mjbvz/test-vscode-ext/raw/main/test.mp4"></video>
```

Unlike the `<img>` tags, the first video's `src` does not get correctly rewritten to point to the extension's GitHub repo

For https://github.com/microsoft/vscode/issues/134514

**Comment by mjbvz** [comment]
To enable this in VS Code too, we'd also want the `/Microsoft.VisualStudio.Services.Content.Details` marketplace API to resolve the video path. It also does this for relative image paths

**Comment by mjbvz** [comment]
If you have `<img src="cat.gif">`, `cat.gif` is correctly rewritten by the marketplace so that is points to `cat.gif` in the extension repo

However if you have `<video src="test.mp4"></video>`, the marketplace does not rewrite anything. This means that `test.mp4` can't be resolved

Note that this also needs to be fixed for the `placeholder` attributed on videos:

```
<video src="test.mp4" placeholder="img.png"></video>
```

**Comment by isidorn** [comment]
@anupkmr03 just informed me the fix for this issue has been pushed.
He will comment here once the fix has been deployed to production. Thanks

**Comment by anupkmr03** [comment]
Hi @mjbvz, we do not update the overview content or any path for image/video. You probably added the complete path for image and local path for video due to that video is not rendered. This is the screenshot of readme.md file from downloaded VSIX. 

![image](https://user-images.githubusercontent.com/16070906/195866610-8fc8b5d5-7a1e-4be7-bbfe-2d3828dbfd10.png)

Can you please re-check your original VSIX overview content. However, I can see your readme.md file on GitHub has the local URL [Readme.md](https://raw.githubusercontent.com/mjbvz/test-vscode-ext/main/README.md)

**Comment by anupkmr03** [comment]
Hi @mjbvz, Sorry if my above reply was confusing, but I was trying to emphasize that you have added the complete URL of image despite that you are assuming that you have added only the local path. However, it isn't the case because we (Marketplace) do not alter the URLs in overview content neither for image nor for videos.
To clarify, I have re-uploaded the same extension with providing local path for both image and video in readme.md file. Both image and video do not load as you can see.

![image](https://user-images.githubusercontent.com/16070906/196053983-b1a892ae-d054-4cb5-8ae6-526e4394b0da.png)

Extension URL : [test-test-copy](https://marketplace.visualstudio.com/items?itemName=AnupKumar.test-test-copy ) you can download and verify the overview content.

**Comment by mjbvz** [comment]
@anupkmr03 Something is rewriting the path. Could it be `vsce` instead? Does your team own the marketplace upload part of that tool?

**Comment by joaomoreno** [comment]
@mjbvz VSCE rewrites README.md media URLs because the Marketplace doesn't serve those. So, when an extension is viewed in the Marketplace page, the URLs are pointing to github.com.

**Comment by mjbvz** [comment]
Got it. Opened https://github.com/microsoft/vscode-vsce/issues/780 to track making VSCE rewrite these
