### ISSUE TITLE
`ERROR The extension 'name' already exists in the Marketplace.` when publishing extension

### ISSUE THREAD

**Issue by Vexu** [microsoft/vsmarketplace#504]
I'm trying to move our extension from the original author's personal publisher account to an organization account as per https://github.com/ziglang/vscode-zig/issues/62#issuecomment-1133499141. Ideally they'd just transfer the extension from `tiehuis.zig` to `ziglang.zig` but I don't know if that's possible or not since I've only found guides about deprecating extensions.

To deprecate the extension I've tried publishing `ziglang.zig` but doing so results in
```
 ERROR  The extension `name` already exists in the Marketplace. Please use a different `name` in the package.json file
```
which doesn't make much sense to me since I know someone else has been able to publish their fork as `prime31.zig`.

What am I missing here?

**Comment by madhurivadaligithub** [comment]
Hi @Vexu We won't support transfer extension from one publisher to other publishers, and to avoid confusion for the end users, the marketplace does not allow publishing extensions with existing names anymore. Hence, we suggest you to please use a different extension name. 

**Suggestions**:  Instead of transfer, you can also do this, the publisher "tiehuis" owner can add required members as owners to the publisher "tiehuis" in future access.

**Comment by gertcuykens** [comment]
<img width="415" alt="image" src="https://user-images.githubusercontent.com/863731/199356723-de0fe4b9-1dbe-41cc-99b9-a16488c237e6.png">
By different extension name you mean the zig language developers can't use the name zig?
Or they have to host it on tiehuis github handle just because you happen to change the naming rules?
So people have to search for let say Zig2 to find the extension from the official source? I understand you don't have enough human resources to administrate the marketplace, but I think your making a mistake here. If you really cant handle the market place anymore I suggest that you introduce domain name validation and use a verified domain as the extension name, and do verification on every update.

**Comment by prashantvc** [comment]
it means you should use a unique name in the `package.json`. See https://code.visualstudio.com/api/references/extension-manifest

**Comment by madhurivadaligithub** [comment]
@Vexu Feel free to create a new ticket if you have any other issues.
