### ISSUE TITLE
Can not Download Extension

### ISSUE THREAD

**Issue by tunahanbg** [microsoft/vsmarketplace#590]
Type: <b>Bug</b>

I can't download extensions. Once I click install, it's installing the extension but when i refresh every extension that I installed is gone. 
I tried the delete VsCode and install again, changing dns, installing from VSIX. These methods didn't work for me.

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: Yes

**Comment by kj0171** [comment]
@tunahanbg 
Can you share more details like console log and also the network tab.
Are you using a VPN client or some local firewall? Can you turn these off and retry?

**Comment by JatinSanghvi** [comment]
Hi @tunahanbg, since the installations made from the VSIX file also does not stick around between VS Code restarts, this seems to be a problem with VS Code installation itself. There are a couple of such issues reported on https://github.com/microsoft/vscode/issues. Can you check if the workaround in https://github.com/microsoft/vscode/issues/174189#issuecomment-1431395066 helps?

**Comment by tunahanbg** [comment]
Hello @JatinSanghvi, thanks for the advice. This issue happend when I updated the Vs Code I forgot the mention that. 
https://github.com/microsoft/vscode/issues, I couldn't find any issues that similar to my issue but thank you anyway.
https://github.com/microsoft/vscode/issues/170336#issuecomment-1368517360, I tried this way too but unfortunately didn't work.

**Comment by tunahanbg** [comment]
@kj0171, thanks for the response. I'm not VPN clint also I tried the disable windows firewall and install extension, but didn't work.
About console log and network tab, I didn't know how to obtain console log so I checked the how to do it. I managed the get it but there is to many information. Could you tell me which part that do you want to see? Same thing for network tab. 
Thank you.

**Comment by JatinSanghvi** [comment]
Hi @tunahanbg, I would suggest you to follow up on the extension install issue on microsoft/vscode repo as the issue does not pertain to hosting of extensions on the VS Marketplace site. I can see a couple of related issues logged in the vscode repo:

https://github.com/microsoft/vscode/issues/174189
https://github.com/microsoft/vscode/issues/171728
https://github.com/microsoft/vscode/issues/171670
https://github.com/microsoft/vscode/issues/170336
https://github.com/microsoft/vscode/issues/169359
https://github.com/microsoft/vscode/issues/169273

You can check out if any of the issues above closely matches to yours, follow any suggestions there, or if your issue turns out to be a novel one, you can create a separate GitHub issue there.

**Comment by JatinSanghvi** [comment]
We will close this one as this issue cannot be fixed from our side.
