### ISSUE TITLE
Unable to Publish Extension

### ISSUE THREAD

**Issue by InTheCloudDan** [microsoft/vsmarketplace#609]
All of the original details in #374 are still applying to us currently trying to publish.

We think we kind of have the root cause, our VSCode extension is here:
https://marketplace.visualstudio.com/items?itemName=LaunchDarklyOfficial.launchdarkly

And ADO: https://marketplace.visualstudio.com/items?itemName=launchdarkly.launchdarkly-extension

We had an issue with access at one point where your team helped us move over at least VSCode, but we thought it was both of them. Looking at the above with one being LaunchDarklyOfficial and the other just launchdarkly it doesn’t appear like ADO moved over. Would we be able to get assistance with that? 

cc @isidorn

**Comment by SaiKanth007** [comment]
Hi @InTheCloudDan 

Can you please help us with the below questions.

1. We see that there are two different publishers on marketplace - LaunchDarklyOfficial, LaunchDarkly - Do you own both of them?
2. Can you also explain a little on which extension are you trying to publish ?
3. Can you share the exact error message you are getting? We are interested in the activityId (if any) mentioned in the error message.
4. Also, I see that @madhurivadaligithub closed the issue #374 since we haven't heard back from you back then. Can you let us know if there was some fix made from our side or you fixed it on your side ?

**Comment by InTheCloudDan** [comment]
@SaiKanth007 

1. Yes, we own both of them, but do not have easy access to the original one which is why we migrated to `LaunchDarklyOfficial`.
2. We are trying to update our AzureDevops integration, it has our old logo: https://marketplace.visualstudio.com/items?itemName=launchdarkly.launchdarkly-extension
3. The error message is 
 
```tfx extension isvalid --publisher launchdarkly --extension-id launchdarkly-extension --version 2.1.25 --service-url https://marketplace.visualstudio.com/ --token <your PAT>
error: Error: Extension validation failed. Please address the following issues and retry publishing.
error: The Service Endpoint Contribution Microsoft.VisualStudio.Services.ServiceEndpointName.LAUNCHDARKLY with Name LAUNCHDARKLY already exists in the Marketplace. To publish the extension, please ensure you have a unique service endpoint name.```

4. Nothing changed we just dropped trying to follow up on it temporarily. Our goal is to get this resolved so we can make additional updates to the extension.

**Comment by SaiKanth007** [comment]
@InTheCloudDan Can you drop an email to vsmarketplace@microsoft.com with the VSIX you are trying to upload.

Also, this issue is related to AzureDevops, @madhurivadaligithub can you please take a look at this.

**Comment by madhurivadaligithub** [comment]
Thanks for reaching VS Marketplace Team, could you please reach out to us through our support alias ([VSMarketplace@microsoft.com](mailto:VSMarketplace@microsoft.com)) to address this issue promptly.
