### ISSUE TITLE
Error while fetching extensions. XHR timeout: undefinedms

### ISSUE THREAD

**Issue by RasyidFT** [microsoft/vsmarketplace#627]
Type: <b>Performance Issue</b>

"The system is unable to connect to Marketplace Extensions even though it has been installed and uninstalled several times."

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 6.2.9200
Modes:
Sandboxed: No

**Comment by xavierdecoster** [comment]
Hi @RasyidFT. Thanks for reporting this issue.

Can you please provide more details so that we can better assist you?
Things that would help us include:
* screenshots or recordings of the issue
* writing out the manual steps to reproduce the issue
* any other relevant context you can share (e.g., behind a network proxy?)

**Comment by madhurivadaligithub** [comment]
Closing the issue as there have been no updates for a week. If the problem persists you can contact us with the requested network log.
