### ISSUE TITLE
Cannot verify publisher when putting in the domain 

### ISSUE THREAD

**Issue by AlexPapageorge-Poly** [microsoft/vsmarketplace#714]
**Describe the bug**
When I go to create publisher and verify the domain when I put in the basic info and copy and paste the domain address in I do not see the save button appear and the verify button remains greyed out. I have tried disabling blockers. 

I am not the manager of the domain. Could it fall under this issue "You must be able to manage the DNS configuration settings and add a TXT record." How do I check and resolve this?

**To Reproduce**
1. Go to '(https://marketplace.visualstudio.com/manage/createpublisher?managePageRedirect=true)'
2. Click on 'sign in & publish extension'
3. Fill in Basic info and Domain https://polyapi.io/
4. See the grey verify button and no option to save appear 

**Expected behavior**
Expected the save option to appear and the ability to click verify. 

**Screenshots**
![image](https://github.com/microsoft/vsmarketplace/assets/128623315/280e8514-ddb5-40fc-b654-c8dcd641c13a)
**Desktop (Mac):**
 - OS: [13.0.1 (22A400)]
 - Browser [Chrome]
 - Version [Version 114.0.5735.133 (Official Build) (arm64)]

**Comment by kareem613** [comment]
Same issue here. 

Chrome and Edge. No ad blocker. 

This appears in the console logs. 

`Refused to connect to 'https://www.google-analytics.com/j/collect?v=1&_v=j101&a=506090167&t=pageview&_s=1&dl=https%3A%2F%2Fmarketplace.visualstudio.com%2Fmanage%2Fcreatepublisher%3FmanagePageRedirect%3Dtrue&dp=https%3A%2F%2Fmarketplace.visualstudio.com%2Fmanage%2Fcreatepublisher%3FmanagePageRedirect%3Dtrue&ul=en-us&de=UTF-8&dt=Create%20Publisher%20%7C%20Visual%20Studio%20Marketplace&sd=24-bit&sr=1920x1080&vp=936x929&je=0&_u=QACAAAABAAAAACAAg~&jid=370884089&gjid=1635707090&cid=986196821.1688132512&tid=UA-62780441-6&_gid=1747645747.1688132512&_r=1&_slc=1&gtm=45He36s0n71WT9XBK&z=2104920812' because it violates the following Content Security Policy directive: "connect-src *.visualstudio.com wss://*.visualstudio.com *.dev.azure.com dev.azure.com wss://*.dev.azure.com wss://dev.azure.com *.vsassets.io vsassetscdn.azure.cn *.blob.core.windows.net *.github.com web.vortex.data.microsoft.com dpm.demdex.net".`

**Comment by madhurivadaligithub** [comment]
Hi @AlexPapageorge-Poly  Are you still facing the same issue?

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
[VS Marketplace policy](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcode.visualstudio.com%2Fapi%2Fworking-with-extensions%2Fpublishing-extension%23verify-a-publisher&data=05%7C02%7Cv-mavadali%40microsoft.com%7C60e267d92b724a26487608dcce53fad3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638612107335018367%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=wbhmpHYl%2B0nfGT%2FMpbTEFSzEpeRduSeyL3dqMvijES4%3D&reserved=0) requires that the extensions need more than 6-month track record of demonstrating extension-relevant content, trust and positive reputation. Since your publisher currently doesn’t have any extensions available, we request that you resubmit your domain verification 6 months after the date of the first extension’s published time period. This will allow us to finalize the approval and notify you. We appreciate your patience. Thank you for applying to become a trusted publisher.

Regards,
VS Marketplace Team
