### ISSUE TITLE
unable to search the marketplace when offline

### ISSUE THREAD

**Issue by ahmad3240** [microsoft/vsmarketplace#829]
![Capture](https://github.com/microsoft/vsmarketplace/assets/152154217/d72005f4-d9a4-4f35-bdcc-f01320a82b3a)
Type: <b>Bug</b>

i cannot install any extension in vs code even my wifi is connected to internet.

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.10240
Modes:

**Comment by madhurivadaligithub** [comment]
Thank you for reaching VS Marketplace Support Team, this issue is specific to VS Code editor and tools, if we understand correctly. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.

Please feel free to reach out to us if you still require any help.

 -VS Marketplace Team
