### ISSUE TITLE
Marketplace Trending extensions filter issue

### ISSUE THREAD

**Issue by madhurivadaligithub** [microsoft/vsmarketplace#866]
**Describe the bug**
This issue is related to "Trending" extensions on the marketplace homepage, it will not show extensions that don't target VS2019.

To Reproduce

1. Go to https://marketplace.visualstudio.com/vs
2. Check the Trending" extensions on the marketplace homepage.

**Expected behavior**
 We should show VS 2022 related extensions on the front page of the Marketplace.

**Screenshots**

**Comment by ErikEJ** [comment]
@madhurivadaligithub  @seaniyer Please 🙏  also fix the related bugs on the forntpage for Most Popular and Highest Rated!

see #547

**Comment by seaniyer** [comment]
As a quick and short-term measure to address security concerns around [Trending] (https://medium.com/@amitassaraf/the-story-of-extensiontotal-how-we-hacked-the-vscode-marketplace-5c6e66a0e9d7), we have removed it from Marketplace web site.  Since the carousel doesn't exist anymore, we can probably close this issue.  The VS Marketplace team will explore introducing a better, more secure version of Trending in the future.
