### ISSUE TITLE
extension page doesn't work with me

### ISSUE THREAD

**Issue by MohamedTBadr** [microsoft/vsmarketplace#903]
Type: <b>Bug</b>

every time i wrote a extension vscode doesn't make search and say timeout

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.21996
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @MohamedTBadr 

Thanks for reaching VS Marketplace Team, could you please share more details about your concern to investigate better.

If you think this issue is specific to vscode, could you please reach out to the VS Code Team https://github.com/microsoft/vscode/issues for further assistance.

Regards,
VS Marketplace Team
