### ISSUE TITLE
Error loading webview

### ISSUE THREAD

**Issue by Fabiano-Vaz** [microsoft/vsmarketplace#908]
Type: <b>Bug</b>

Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:16:23.416Z)
OS version: Linux x64 6.2.0-39-generic
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @Fabiano-Vaz 

Thanks for reaching VS Marketplace Team, could you please share more details about your concern to investigate better.

If you think this issue is specific to vscode, could you please reach out to the VS Code Team https://github.com/microsoft/vscode/issues for further assistance.

Regards,
VS Marketplace Team
