### ISSUE TITLE
Failed to install/update extension

### ISSUE THREAD

**Issue by MoMeakDong** [microsoft/vsmarketplace#909]
When I prepare to update or install extensions, this error net::ERR_INVALID_ARGUMENT: always appears, causing me to fail; but I checked that there is no problem with the network.

VS Code version: Code 1.89.1 (Universal) (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:14:24.611Z)
OS version: Darwin arm64 21.2.0
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @MoMeakDong ,

Thanks for reaching VS Marketplace Team, could you please share more details about your concern to investigate better.

If you think this issue is specific to vscode, could you please reach out to the VS Code Team https://github.com/microsoft/vscode/issues for further assistance.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Since we have not received the required information, we are closing the issue. Please feel free to reopen or create a new issue if the problem still persists.

Regards,
VS Marketplace Team
