### ISSUE TITLE
microsoft unity extension not working with unity 2022.3.33.f1:  doesn't get registered as a external script editor

### ISSUE THREAD

**Issue by alanbork** [microsoft/vsmarketplace#942]
Type: <b>Bug</b>

I'm using a fresh install of Unity 2022.3.33f1 and after following the instructions for adding unity support to vs code (using microsoft's own supported extension, https://code.visualstudio.com/docs/other/unity) there's no option to select visual studio code as the external script editor. My only options are open by extension and browse.

I've tried every combination of visual studio related unity packages: vscode 1.25 and vs editor 2.0.22 and the list of script editors never changes.

this is in a project created in unity 2021.3, which worked great using the vscode package and vscode microsoft extension, but I had to start over from scratch when my HD died, and I'm not sure if I missed a step or if the vscode support is broken again since version 2022?

and yes, while "open by extension" works in the sense that I can use vs code to edit my scripts all the intellisense is missing. 

VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @alanbork ,

This issue seems to be specific to the extension and is best handled by the extension’s maintainer. Please visit the extension’s page on Visual Studio Marketplace and post your query there, and let us know for any assistance required.

Additionally, for VS Code editor and tool, It is best to reach out VS Code team at  https://github.com/microsoft/vscode/issues.

Regards,
VS Marketplace Team
